{% extends "../layouts/two-column-left.phtml" %}

{% block title %}{{ title }}{% endblock %}

{% block menu %}
	{% include '/../layouts/partials/menu-user.phtml' %}
{% endblock %}

{% block content %}
	<div class="row margin-bottom-lg">
		<?php
			echo $this->tag->linkTo(array(
				'fit/add/character/' . $char->id,
				'<i class="fa fa-plus"></i> Add Fit',
				'class' => 'btn btn-success pull-left',
			));
		?>
	</div>

	<h2><?php echo $title; ?></h2>

	<?php
		if($page->items) echo $this->pagination->getRow($page, 'Fits', $this->url->get($page->meta->baseLink . $page->meta->pageLink));
	?>
	<div class="table-responsive">
		<table class="table table-condensed table-hover">
			<tr class="background-gray">
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'ID', 'fid'); ?></th>
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Name', 'name'); ?></th>
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Type', 'type'); ?></th>
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Date Created', 'date'); ?></th>
                <th></th>
                <th></th>
            </tr>
	        <?php
	            if($page->items) {
	                foreach($page->items as $fit) {
						?>
							<tr>
								<td><?php echo $fit->id; ?></td>
								<td><?php echo $fit->name; ?></td>
								<td><?php echo $fit->type->name; ?></td>
								<td><?php echo $fit->date_created; ?></td>
								<td>
									<?php
										echo $this->tag->linkTo(array(
											'fit/details/' . $fit->id,
											'<i class="fa fa-tasks"></i> Details',
											'class' => 'btn btn-info btn-sm pull-left margin-right-xs',
										));
									?>
								</td>
								<td>
									<?php
										echo $this->tag->linkTo(array(
											'fit/delete/' . $fit->id,
											'<i class="fa fa-trash-o"></i> Delete',
											'class' => 'btn btn-danger btn-sm pull-left margin-right-xs',
										));
									?>
								</td>
							</tr>
						<?php
	                }
	            }
			?>
		</table>
	</div>
{% endblock %}

