{% extends "../layouts/two-column-left.phtml" %}

{% block title %}{{ title }}{% endblock %}

{% block menu %}
	{% include '/../layouts/partials/menu-user.phtml' %}
{% endblock %}

{% block content %}
	<div class="row">
		{{ partial('forms/mission/selector', ['form':mission_form]) }}
	</div>

	<div class="row">
		<h3><?php echo $title; ?></h3>
	</div>

	<div class="row margin-bottom-lg">
		{{ partial('forms/mission/add-to-list', ['form':add_form]) }}
	</div>

	<?php
		if($page->items) echo $this->pagination->getRow($page, 'Fits', $this->url->get($page->meta->baseLink . $page->meta->pageLink));
	?>
	<div class="table-responsive">
		<table class="table table-condensed table-hover">
			<tr class="background-gray">
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Character ID', 'cid'); ?></th>
				<th>Character Info</th>
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Waiting Since', 'date'); ?></th>
				<th><?php echo $this->pagination->sortByLink($page->meta, $page->meta->baseLink, 'Fit ID', 'fid'); ?></th>
				<th>Fit Name</th>
				<th>Fit Details</th>
                <th></th>
            </tr>
	        <?php
	            if($page->items) {
	                foreach($page->items as $player) {
						?>
							<tr>
								<td><?php echo $player->character_id; ?></td>
								<td>
									<button class="btn btn-sm btn-warning" type="button" onclick="CCPEVE.showInfo(1377, <?php $player->character->id ?>>)">
										<?php echo $player->character->name; ?>
									</button>
								</td>
								<td><?php echo $player->date_created; ?></td>
								<td><?php echo $player->fit_id; ?></td>
								<td><?php echo $player->fit->name; ?></td>
								<td>
									<?php
										echo $this->tag->linkTo(array(
											'fit/details/' . $player->fit->id,
											'<i class="fa fa-tasks"></i> Details',
											'class' => 'btn btn-info btn-sm pull-left margin-right-xs',
										));
									?>
								</td>
								<td>
									<?php
										if(
											$this->session->get('auth')->role->role == 'admin' ||
											$this->session->get('auth')->id == $player->character->user_id
										) {
											echo $this->tag->linkTo(array(
												'mission/remove-player/' . $player->id,
												'<i class="fa fa-power-off"></i> Remove from list',
												'class' => 'btn btn-danger btn-sm pull-left margin-right-xs',
											));
										}
									?>
								</td>
							</tr>
						<?php
	                }
	            }
			?>
		</table>
	</div>
{% endblock %}

