<header class="header hidden-xs margin-top-md">
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="logo">
                    <a href="<?php echo $this->url->get('') ?>">
                    	<img src="/images/icons/logo.png" />
                    </a>
                    <p>Page name and some logo here</p>
                </div>
            </div>
            <div class="col-sm-6 col-md-6 col-lg-6">
                <div class="text-right action clearfix">
                    {% include "/../layouts/partials/login.phtml" %}
                </div>
            </div>
        </div>
    </div>
</header>